/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Serv_H
#define Serv_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "student_types.h"



#ifdef _WIN32
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class ServIf {
 public:
  virtual ~ServIf() {}
  virtual void put(const Student& s) = 0;
  virtual int32_t icall(const Student& s) = 0;
  virtual void scall(std::string& _return, const Student& s) = 0;
  virtual void stcall(Student& _return, const Student& s) = 0;
};

class ServIfFactory {
 public:
  typedef ServIf Handler;

  virtual ~ServIfFactory() {}

  virtual ServIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(ServIf* /* handler */) = 0;
};

class ServIfSingletonFactory : virtual public ServIfFactory {
 public:
  ServIfSingletonFactory(const boost::shared_ptr<ServIf>& iface) : iface_(iface) {}
  virtual ~ServIfSingletonFactory() {}

  virtual ServIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(ServIf* /* handler */) {}

 protected:
  boost::shared_ptr<ServIf> iface_;
};

class ServNull : virtual public ServIf {
 public:
  virtual ~ServNull() {}
  void put(const Student& /* s */) {
    return;
  }
  int32_t icall(const Student& /* s */) {
    int32_t _return = 0;
    return _return;
  }
  void scall(std::string& /* _return */, const Student& /* s */) {
    return;
  }
  void stcall(Student& /* _return */, const Student& /* s */) {
    return;
  }
};

typedef struct _Serv_put_args__isset {
  _Serv_put_args__isset() : s(false) {}
  bool s :1;
} _Serv_put_args__isset;

class Serv_put_args {
 public:

  Serv_put_args(const Serv_put_args&);
  Serv_put_args& operator=(const Serv_put_args&);
  Serv_put_args() {
  }

  virtual ~Serv_put_args() throw();
  Student s;

  _Serv_put_args__isset __isset;

  void __set_s(const Student& val);

  bool operator == (const Serv_put_args & rhs) const
  {
    if (!(s == rhs.s))
      return false;
    return true;
  }
  bool operator != (const Serv_put_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Serv_put_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Serv_put_pargs {
 public:


  virtual ~Serv_put_pargs() throw();
  const Student* s;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Serv_put_result {
 public:

  Serv_put_result(const Serv_put_result&);
  Serv_put_result& operator=(const Serv_put_result&);
  Serv_put_result() {
  }

  virtual ~Serv_put_result() throw();

  bool operator == (const Serv_put_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const Serv_put_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Serv_put_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Serv_put_presult {
 public:


  virtual ~Serv_put_presult() throw();

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Serv_icall_args__isset {
  _Serv_icall_args__isset() : s(false) {}
  bool s :1;
} _Serv_icall_args__isset;

class Serv_icall_args {
 public:

  Serv_icall_args(const Serv_icall_args&);
  Serv_icall_args& operator=(const Serv_icall_args&);
  Serv_icall_args() {
  }

  virtual ~Serv_icall_args() throw();
  Student s;

  _Serv_icall_args__isset __isset;

  void __set_s(const Student& val);

  bool operator == (const Serv_icall_args & rhs) const
  {
    if (!(s == rhs.s))
      return false;
    return true;
  }
  bool operator != (const Serv_icall_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Serv_icall_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Serv_icall_pargs {
 public:


  virtual ~Serv_icall_pargs() throw();
  const Student* s;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Serv_icall_result__isset {
  _Serv_icall_result__isset() : success(false) {}
  bool success :1;
} _Serv_icall_result__isset;

class Serv_icall_result {
 public:

  Serv_icall_result(const Serv_icall_result&);
  Serv_icall_result& operator=(const Serv_icall_result&);
  Serv_icall_result() : success(0) {
  }

  virtual ~Serv_icall_result() throw();
  int32_t success;

  _Serv_icall_result__isset __isset;

  void __set_success(const int32_t val);

  bool operator == (const Serv_icall_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Serv_icall_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Serv_icall_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Serv_icall_presult__isset {
  _Serv_icall_presult__isset() : success(false) {}
  bool success :1;
} _Serv_icall_presult__isset;

class Serv_icall_presult {
 public:


  virtual ~Serv_icall_presult() throw();
  int32_t* success;

  _Serv_icall_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Serv_scall_args__isset {
  _Serv_scall_args__isset() : s(false) {}
  bool s :1;
} _Serv_scall_args__isset;

class Serv_scall_args {
 public:

  Serv_scall_args(const Serv_scall_args&);
  Serv_scall_args& operator=(const Serv_scall_args&);
  Serv_scall_args() {
  }

  virtual ~Serv_scall_args() throw();
  Student s;

  _Serv_scall_args__isset __isset;

  void __set_s(const Student& val);

  bool operator == (const Serv_scall_args & rhs) const
  {
    if (!(s == rhs.s))
      return false;
    return true;
  }
  bool operator != (const Serv_scall_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Serv_scall_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Serv_scall_pargs {
 public:


  virtual ~Serv_scall_pargs() throw();
  const Student* s;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Serv_scall_result__isset {
  _Serv_scall_result__isset() : success(false) {}
  bool success :1;
} _Serv_scall_result__isset;

class Serv_scall_result {
 public:

  Serv_scall_result(const Serv_scall_result&);
  Serv_scall_result& operator=(const Serv_scall_result&);
  Serv_scall_result() : success() {
  }

  virtual ~Serv_scall_result() throw();
  std::string success;

  _Serv_scall_result__isset __isset;

  void __set_success(const std::string& val);

  bool operator == (const Serv_scall_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Serv_scall_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Serv_scall_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Serv_scall_presult__isset {
  _Serv_scall_presult__isset() : success(false) {}
  bool success :1;
} _Serv_scall_presult__isset;

class Serv_scall_presult {
 public:


  virtual ~Serv_scall_presult() throw();
  std::string* success;

  _Serv_scall_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Serv_stcall_args__isset {
  _Serv_stcall_args__isset() : s(false) {}
  bool s :1;
} _Serv_stcall_args__isset;

class Serv_stcall_args {
 public:

  Serv_stcall_args(const Serv_stcall_args&);
  Serv_stcall_args& operator=(const Serv_stcall_args&);
  Serv_stcall_args() {
  }

  virtual ~Serv_stcall_args() throw();
  Student s;

  _Serv_stcall_args__isset __isset;

  void __set_s(const Student& val);

  bool operator == (const Serv_stcall_args & rhs) const
  {
    if (!(s == rhs.s))
      return false;
    return true;
  }
  bool operator != (const Serv_stcall_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Serv_stcall_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Serv_stcall_pargs {
 public:


  virtual ~Serv_stcall_pargs() throw();
  const Student* s;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Serv_stcall_result__isset {
  _Serv_stcall_result__isset() : success(false) {}
  bool success :1;
} _Serv_stcall_result__isset;

class Serv_stcall_result {
 public:

  Serv_stcall_result(const Serv_stcall_result&);
  Serv_stcall_result& operator=(const Serv_stcall_result&);
  Serv_stcall_result() {
  }

  virtual ~Serv_stcall_result() throw();
  Student success;

  _Serv_stcall_result__isset __isset;

  void __set_success(const Student& val);

  bool operator == (const Serv_stcall_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Serv_stcall_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Serv_stcall_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Serv_stcall_presult__isset {
  _Serv_stcall_presult__isset() : success(false) {}
  bool success :1;
} _Serv_stcall_presult__isset;

class Serv_stcall_presult {
 public:


  virtual ~Serv_stcall_presult() throw();
  Student* success;

  _Serv_stcall_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class ServClient : virtual public ServIf {
 public:
  ServClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  ServClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void put(const Student& s);
  void send_put(const Student& s);
  void recv_put();
  int32_t icall(const Student& s);
  void send_icall(const Student& s);
  int32_t recv_icall();
  void scall(std::string& _return, const Student& s);
  void send_scall(const Student& s);
  void recv_scall(std::string& _return);
  void stcall(Student& _return, const Student& s);
  void send_stcall(const Student& s);
  void recv_stcall(Student& _return);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class ServProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<ServIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (ServProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_put(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_icall(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_scall(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_stcall(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  ServProcessor(boost::shared_ptr<ServIf> iface) :
    iface_(iface) {
    processMap_["put"] = &ServProcessor::process_put;
    processMap_["icall"] = &ServProcessor::process_icall;
    processMap_["scall"] = &ServProcessor::process_scall;
    processMap_["stcall"] = &ServProcessor::process_stcall;
  }

  virtual ~ServProcessor() {}
};

class ServProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  ServProcessorFactory(const ::boost::shared_ptr< ServIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< ServIfFactory > handlerFactory_;
};

class ServMultiface : virtual public ServIf {
 public:
  ServMultiface(std::vector<boost::shared_ptr<ServIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~ServMultiface() {}
 protected:
  std::vector<boost::shared_ptr<ServIf> > ifaces_;
  ServMultiface() {}
  void add(boost::shared_ptr<ServIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void put(const Student& s) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->put(s);
    }
    ifaces_[i]->put(s);
  }

  int32_t icall(const Student& s) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->icall(s);
    }
    return ifaces_[i]->icall(s);
  }

  void scall(std::string& _return, const Student& s) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->scall(_return, s);
    }
    ifaces_[i]->scall(_return, s);
    return;
  }

  void stcall(Student& _return, const Student& s) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->stcall(_return, s);
    }
    ifaces_[i]->stcall(_return, s);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class ServConcurrentClient : virtual public ServIf {
 public:
  ServConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  ServConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void put(const Student& s);
  int32_t send_put(const Student& s);
  void recv_put(const int32_t seqid);
  int32_t icall(const Student& s);
  int32_t send_icall(const Student& s);
  int32_t recv_icall(const int32_t seqid);
  void scall(std::string& _return, const Student& s);
  int32_t send_scall(const Student& s);
  void recv_scall(std::string& _return, const int32_t seqid);
  void stcall(Student& _return, const Student& s);
  int32_t send_stcall(const Student& s);
  void recv_stcall(Student& _return, const int32_t seqid);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _WIN32
  #pragma warning( pop )
#endif



#endif
